In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv(r"C:\Users\yuvas\OneDrive\Desktop\PDA\Walmart Data Analysis and Forcasting.csv")

In [5]:
df.head()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,05-02-2010,"$16,43,690.90",0,42.31,$2.57,211.096358,8.106
1,1,12-02-2010,"$16,41,957.44",1,38.51,$2.55,211.242170,8.106
2,1,19-02-2010,"$16,11,968.17",0,39.93,$2.51,211.289143,8.106
3,1,26-02-2010,"$14,09,727.59",0,46.63,$2.56,211.319643,8.106
4,1,05-03-2010,"$15,54,806.68",0,46.50,$2.63,211.350143,8.106

In [6]:
df.tail()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
6430,45,28-09-2012,"$7,13,173.95",0,64.88,$4.00,192.013558,8.684
6431,45,05-10-2012,"$7,33,455.07",0,64.89,$3.99,192.170412,8.667
6432,45,12-10-2012,"$7,34,464.36",0,54.47,$4.00,192.327265,8.667
6433,45,19-10-2012,"$7,18,125.53",0,56.47,$3.97,192.330854,8.667
6434,45,26-10-2012,"$7,60,281.43",0,58.85,$3.88,192.308899,8.667

In [7]:
df.shape

(6435, 8)

In [8]:
df.columns

Index(['Store', 'Date', ' Weekly_Sales ', 'Holiday_Flag', 'Temperature',
       ' Fuel_Price ', 'CPI', 'Unemployment'],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6435 entries, 0 to 6434
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Store           6435 non-null   int64
 1   Date            6435 non-null   object
 2    Weekly_Sales   6435 non-null   object
 3   Holiday_Flag    6435 non-null   int64
 4   Temperature     6435 non-null   float64
 5    Fuel_Price     6435 non-null   object
 6   CPI             6435 non-null   float64
 7   Unemployment    6435 non-null   float64
dtypes: float64(3), int64(2), object(3)
memory usage: 402.3+ KB

In [11]:
df.columns = df.columns.str.strip()

In [12]:
print(df.columns)

Index(['Store', 'Date', 'Weekly_Sales', 'Holiday_Flag', 'Temperature',
       'Fuel_Price', 'CPI', 'Unemployment'],
      dtype='object')

In [13]:
df["Weekly_Sales"].head()

0     $16,43,690.90
1     $16,41,957.44
2     $16,11,968.17
3     $14,09,727.59
4     $15,54,806.68
Name: Weekly_Sales, dtype: object

In [ ]:
df["Weekly_Sales"] = df["Weekly_Sales"].str.replace("$", "", regex=False)
df["Weekly_Sales"] = df["Weekly_Sales"].str.replace(",", "", regex=False)

In [ ]:
df["Weekly_Sales"] = pd.to_numeric(df["Weekly_Sales"])

In [14]:
df["Fuel_Price"].head()

0     $2.57
1     $2.55
2     $2.51
3     $2.56
4     $2.63
Name: Fuel_Price, dtype: object

In [ ]:
df["Fuel_Price"] = df["Fuel_Price"].str.replace("$", "", regex=False)

In [15]:
df["Fuel_Price"] = pd.to_numeric(df["Fuel_Price"])

ValueError: Unable to parse string " $2.57 " at position 0

In [ ]:
f["Date"] = pd.to_datetime(df["Date"], format="%d-%m-%Y")d

In [16]:
df.isnull().sum()

Store           0
Date            0
Weekly_Sales    0
Holiday_Flag    0
Temperature     0
Fuel_Price      0
CPI             0
Unemployment    0
dtype: int64

In [17]:
df.isnull().sum().sum()

np.int64(0)

In [18]:
df = df.dropna()

In [19]:
df["CPI"] = df["CPI"].fillna(df["CPI"].mean())
df["Unemployment"] = df["Unemployment"].fillna(df["Unemployment"].mean())

In [ ]:
df = df.fillna(0)

In [20]:
df.duplicated().sum()

np.int64(0)

In [21]:
df[df.duplicated()]

Empty DataFrame
Columns: [Store, Date, Weekly_Sales, Holiday_Flag, Temperature, Fuel_Price, CPI, Unemployment]
Index: []

In [22]:
df = df.drop_duplicates()

In [23]:
df.describe()

             Store  Holiday_Flag  Temperature          CPI  Unemployment
count  6435.000000   6435.000000  6435.000000  6435.000000   6435.000000
mean     23.000000      0.069930    60.663782   171.578394      7.999151
std      12.988182      0.255049    18.444933    39.356712      1.875885
min       1.000000      0.000000    -2.060000   126.064000      3.879000
25%      12.000000      0.000000    47.460000   131.735000      6.891000
50%      23.000000      0.000000    62.670000   182.616521      7.874000
75%      34.000000      0.000000    74.940000   212.743293      8.622000
max      45.000000      1.000000   100.140000   227.232807     14.313000

In [ ]:
df['Weekly_Sales'].mean()

In [ ]:
df['Weekly_Sales'].max()

In [ ]:
df['Weekly_Sales'].min()

In [29]:
df.groupby("Store")["Weekly_Sales"].mean()

TypeError: agg function failed [how->mean,dtype->object]

In [30]:
df.groupby("Store")["Weekly_Sales"].sum()

Store
1      $16,43,690.90  $16,41,957.44  $16,11,968.17  ...
2      $21,36,989.46  $21,37,809.50  $21,24,451.54  ...
3      $4,61,622.22  $4,20,728.96  $4,21,642.19  $4,...
4      $21,35,143.87  $21,88,307.39  $20,49,860.26  ...
5      $3,17,173.10  $3,11,825.70  $3,03,447.57  $2,...
6      $16,52,635.10  $16,06,283.86  $15,67,138.07  ...
7      $4,96,725.44  $5,24,104.92  $5,06,760.54  $4,...
8      $10,04,137.09  $9,94,801.40  $9,63,960.37  $8...
9      $5,49,505.55  $5,52,677.48  $5,11,327.90  $4,...
10     $21,93,048.75  $21,76,028.52  $21,13,432.58  ...
11     $15,28,008.64  $15,74,684.08  $15,03,298.70  ...
12     $11,00,046.37  $11,17,863.33  $10,95,421.65  ...
13     $19,67,220.53  $20,30,933.46  $19,70,274.64  ...
14     $26,23,469.95  $17,04,218.84  $22,04,556.70  ...
15     $6,52,122.44  $6,82,447.10  $6,60,838.75  $5,...
16     $4,77,409.30  $4,72,044.28  $4,69,868.70  $4,...
17     $7,89,036.02  $8,41,951.91  $8,00,714.00  $7,...
18     $12,05,307.50  $11,87,880.70  $11,50,663.42  ...
19     $15,07,637.17  $15,36,549.95  $15,15,976.11  ...
20     $24,01,395.47  $21,09,107.90  $21,61,549.76  ...
21     $7,98,593.88  $8,09,321.44  $8,67,283.25  $7,...
22     $10,33,017.37  $10,22,571.25  $9,88,467.61  $...
23     $13,64,721.58  $13,80,892.08  $13,19,588.04  ...
24     $13,88,725.63  $14,14,107.10  $13,85,362.49  ...
25     $6,77,231.63  $5,83,364.02  $6,76,260.67  $6,...
26     $10,34,119.21  $10,15,684.09  $9,99,348.55  $...
27     $18,74,289.79  $17,45,362.72  $19,45,070.33  ...
28     $16,72,352.29  $15,58,968.49  $14,91,300.42  ...
29     $5,38,634.46  $5,29,672.95  $5,42,399.07  $4,...
30     $4,65,108.52  $4,97,374.57  $4,63,513.26  $4,...
31     $14,69,252.05  $15,43,947.23  $14,73,386.75  ...
32     $10,87,616.19  $11,23,566.12  $10,82,559.06  ...
33     $2,74,593.43  $2,94,882.83  $2,96,850.83  $2,...
34     $9,56,228.96  $9,94,610.99  $9,83,963.07  $9,...
35     $12,30,613.50  $11,68,815.31  $12,70,658.64  ...
36     $4,67,546.74  $4,69,563.70  $4,70,281.03  $4,...
37     $5,36,006.73  $5,29,852.70  $5,10,382.50  $5,...
38     $3,58,496.14  $3,42,214.90  $3,27,237.92  $3,...
39     $12,30,596.80  $12,66,229.07  $12,30,591.97  ...
40     $10,01,943.80  $9,55,338.29  $9,16,289.20  $8...
41     $10,86,533.18  $10,75,656.34  $10,52,034.74  ...
42     $5,43,384.01  $5,75,709.96  $5,08,794.87  $4,...
43     $6,47,029.28  $6,82,918.99  $6,58,997.55  $6,...
44     $2,81,090.95  $2,86,857.13  $2,67,956.30  $2,...
45     $8,90,689.51  $6,56,988.64  $8,41,264.04  $7,...
Name: Weekly_Sales, dtype: object